"""Weather demo: AMap query + DeepSeek natural-language summary.

Goals:
1) Learn how to call a third-party HTTP API (AMap weather).
2) Learn how to pass structured JSON to an LLM for readable summarization.
3) Learn a minimal two-step flow: data retrieval -> LLM summary.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import sys
from pathlib import Path
from urllib import request
from urllib.parse import quote

if __package__ is None or __package__ == "":
    # Keep imports working when running this file directly:
    # python src/ai_agent/learning/stage_00_foundation/weather_info_demo.py
    #
    # Current file path:
    # .../AI_Agent/src/ai_agent/learning/stage_00_foundation/weather_info_demo.py
    # parents[3] points to .../AI_Agent/src
    sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from ai_agent.config.settings import settings


@dataclass
class WeatherClient:
    """AMap weather API client.

    Single responsibility: fetch raw weather JSON only.
    """

    base_url: str
    api_key: str
    timeout: int = 60

    def get_weather_info(self, city_name: str) -> dict:
        """Fetch AMap weather JSON by city name.

        Args:
            city_name: City name, e.g. "Beijing" / "Xingning".

        Returns:
            dict: Raw JSON dictionary returned by AMap API.
        """
        # City names may contain non-ASCII chars, so URL encoding is required.
        city_encoded = quote(city_name, safe="")

        # Notes:
        # - weatherInfo: AMap weather endpoint path
        # - extensions=all: include forecast data
        # - output=json: JSON output format
        # - key: your AMap key from private.local.yaml
        url = (
            f"{self.base_url.rstrip('/')}/weatherInfo"
            f"?city={city_encoded}&extensions=all&output=json&key={self.api_key}"
        )

        # Use urllib here as a minimal HTTP GET example.
        req = request.Request(
            url,
            method="GET",
            headers={
                "Content-Type": "application/json",
            },
        )

        # Decode response body into JSON.
        with request.urlopen(req, timeout=self.timeout) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        return body


@dataclass
class DeepSeekClient:
    """DeepSeek client for summarizing weather JSON."""

    base_url: str
    api_key: str
    model: str = "deepseek-chat"
    timeout: int = 60

    def summarize_weather(self, weather_info: dict) -> str:
        """Convert weather JSON into concise natural language text.

        Args:
            weather_info: Raw weather JSON from WeatherClient.

        Returns:
            str: Readable summary generated by the LLM.
        """
        # The system prompt defines output style and constraints.
        system_prompt = (
            "你是一个简洁天气助手。"
            "请将给定的天气 JSON 解析成简洁自然语言。"
            "需要包含当前时间、省市信息、天气、温度范围、风向风力等会比较影响用户出行的信息。"
            "若有未来几天天气，请补充一句趋势。"
            "不要输出思考过程。"
        )

        # Minimal DeepSeek Chat Completions payload:
        # - model: model name
        # - temperature: 0 for stable output
        # - messages: system + user
        #
        # ensure_ascii=False keeps Chinese characters readable in JSON.
        payload = {
            "model": self.model,
            "temperature": 0,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(weather_info, ensure_ascii=False)},
            ],
        }

        # Standard DeepSeek chat completions endpoint.
        endpoint = f"{self.base_url.rstrip('/')}/chat/completions"

        # Authorization with Bearer token.
        req = request.Request(
            endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {self.api_key}",
            },
            method="POST",
        )

        # Parse response and extract assistant text output.
        with request.urlopen(req, timeout=self.timeout) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        return body["choices"][0]["message"]["content"].strip()


def main(city: str | None = None) -> None:
    """Program entrypoint: weather query -> LLM summary."""
    # 1) Read service config from centralized settings (AMap + DeepSeek).
    amap_cfg = settings.services.get("amap_weather", {})
    deepseek_cfg = settings.services.get("deepseek", {})

    # 2) Initialize two clients with separate responsibilities.
    weather_client = WeatherClient(
        base_url=amap_cfg.get("base_url", ""),
        api_key=amap_cfg.get("api_key", ""),
    )
    llm_client = DeepSeekClient(
        base_url=deepseek_cfg.get("base_url", ""),
        api_key=deepseek_cfg.get("api_key", ""),
    )

    # 3) City source:
    # - Prefer CLI args (supports spaces)
    # - Fallback default: "Beijing"
    cli_city = " ".join(sys.argv[1:]).strip()
    city_name = city or cli_city or "北京"

    # 4) Fetch raw weather JSON from AMap.
    weather_info = weather_client.get_weather_info(city_name)

    # 5) Send JSON to DeepSeek and get a concise summary.
    summary = llm_client.summarize_weather(weather_info)

    # 6) Print final result.
    print(summary)


if __name__ == "__main__":
    main("广州")
